METATAG_KEYWORDS = [
  "Tsunami",
  "Earthquake",
  "Drought",
  "Preparedness",
  "Preparedness Kit",
  "Make a Kit",
  "Get Prepared",
  "Ready Gov",
  "Ready SF",
  "San Francisco NERT",
  "Fire",
  "Shelter In Place",
  "Evacuation",
  "Prepared",
  "Make a Plan",
  "SF Crisis",
  "Disaster Plan",
  "SF Disaster",
  "Emergency",
  "SF Emergency",
  "Emergency Plan",
  "Emergency Kit",
  "Family Preparedness",
  "Personal Preparedness",
  "Pet Preparedness",
  "72 Hours",
  "72 Hour Kit",
  "Zombie Apocalypse in SF",
  "Storm",
  "Flood",
  "Flooding",
  "Terrorism",
  "IED in SF",
  "Duct Tape",
  "San Francisco",
  "Bay Area",
  "Noe Valley",
  "Presido",
  "Portero Hill",
  "Marina",
  "Fisherman's Wharf",
  "Richmond",
  "Cow Hollow",
  "Chinatown",
  "SOMA",
  "Civic Center",
  "Glen Park",
  "Bernal Heights",
  "Tenderloin",
  "Russian Hill",
  "Nob Hill",
  "Union Square",
  "Bayview",
  "Diamond Heights",
  "Haight-Ashbury",
  "Teraval",
  "Ingleside",
  "Hunter's Point",
  "Mission",
  "China Basin",
  "Lake Merced",
  "Forest Hill",
  "Twin Peaks",
  "Financial District",
  "Castro",
  "Sunset",
  "Treasure Island",
  "Golden Gate preparedness",
  "Private Sector preparedness",
  "SF CERT",
  "NERT"
].join(',')